"""Explicit long-report composition, sharing the core renderer's numbers, tables and SVGs.

No page-count target, external assets, JavaScript or inferred business claims.
The caller supplies a reviewed page plan. Browser/PDF overflow must be checked separately.
"""
from __future__ import annotations
from itertools import groupby
import re
from report_tools import ROOT, E, P, metric_text, source_refs, table_html, chart_svg


def linked(text: str, report: dict) -> str:
    out=P(text)
    known={s['id'] for s in report['sections']} | {a['id'] for a in report['actions']}
    if known:
        expr=r'(?<![\w-])('+ '|'.join(sorted(map(re.escape,known),key=len,reverse=True)) +r')(?![\w-])'
        out=re.sub(expr,lambda m:f'<a class="xref" href="#{E(m[0])}">{E(m[0])}</a>',out)
    return out


def render_composed(report: dict) -> str:
    m=report['meta'];su=report['summary'];plan=report['composition']['pages']
    css=(ROOT/'assets/report.css').read_text(encoding='utf-8')+'\n'+(ROOT/'assets/long-report.css').read_text(encoding='utf-8')
    sections={s['id']:s for s in report['sections']};actions={a['id']:a for a in report['actions']};sources={s['id']:s for s in report['sources']}
    total=len(plan);toc_id=next((p['id'] for p in plan if p['kind']=='toc'),plan[0]['id'])
    tag='合成数据演示｜非真实经营结论' if m['synthetic'] else '内部报告'
    if m['status']=='partial':tag+='｜阶段性结果'
    def q(t):return linked(t,report)
    def content(s):
        paras=''.join(f'<p>{q(p)}</p>' for p in s['paragraphs'])
        fig=chart_svg(s['chart'],report,s['id'],dense=True) if 'chart' in s else ''
        table=table_html(s['table'],report) if 'table' in s else ''
        points=s.get('evidence_points',[])
        evidence=''.join(f'<li><b>{E(p["id"])}</b> {q(p["statement"])} <span>{source_refs(p["source_ids"])}</span></li>' for p in points[:2])
        evidence=f'<div class="section-evidence"><h3>关键证据</h3><ul>{evidence}</ul></div>' if evidence else ''
        reasoning=s.get('reasoning')
        explanation=(f'<div class="section-reasoning"><p><b>解释：</b>{q(reasoning["interpretation"])}</p>'
                     f'<p><b>待排除：</b>{q("；".join(reasoning["alternatives"]))}</p></div>') if reasoning else ''
        # Link only text nodes generated by the trusted table builder. No input markup is accepted.
        if table:
            table=re.sub(r'<td>(.*?)</td>',lambda mt:'<td>'+re.sub(r'(?<![\w-])([AD]\d{2})(?![\w-])',lambda x:f'<a class="xref" href="#{x[0]}">{x[0]}</a>' if x[0] in sections or x[0] in actions else x[0],mt[1])+'</td>',table)
        return f'<div id="{E(s["id"])}"><p class="eyebrow">{E(s["eyebrow"])}</p><h2 class="section-title">{E(s["headline"])}</h2>{fig or evidence}<div class="narrative">{paras}</div>{table}{explanation}<p class="implication"><b>业务含义与下一步：</b>{q(s["implication"])}</p><p class="caveat"><b>适用边界：</b>{q(s["limitation"])}</p><p class="source">资料来源：{source_refs(s["source_ids"])}。详细口径见来源索引。</p></div>'
    def action(a):
        state='建议方案，尚未批准' if a['status']=='proposed' else '已批准'
        links='、'.join(f'<a href="#{E(x)}">{E(x)}</a>' for x in a['related_sections'])
        fields=[('依据与目标',a['rationale']),('责任／时间',a['owner']+'；'+a['timing']),('交付与验收',a['success']),('继续／停止',a['gate']),('前置依赖',a['dependencies'])]
        dl=''.join(f'<dt>{E(k)}</dt><dd>{q(v)}</dd>' for k,v in fields)
        return f'<article class="action" id="{E(a["id"])}"><p class="action-status">{E(a["id"])} · {state} · 证据 {links}</p><h3>{E(a["title"])}</h3><dl>{dl}</dl></article>'
    def page_range(predicate):
        nums=[i for i,p in enumerate(plan,1) if predicate(p)]
        if not nums:return '相关'
        return str(nums[0]) if len(nums)==1 else f'{nums[0]}—{nums[-1]}'
    summary_chapter=next(p['chapter'] for p in plan if p['kind']=='summary')
    management=page_range(lambda p:p['chapter']==summary_chapter)
    execution=page_range(lambda p:p['kind']=='actions')
    methods=page_range(lambda p:p['kind']=='sources' or any(x.startswith('M') for x in p.get('section_ids',[])))
    demo_note='这是长报告的合成示例，材料覆盖状态指示的是示例输入是否足以支持判断，不代表对任何真实店铺完成了审计。' if m['synthetic'] else '材料覆盖状态说明现有证据支持的范围，不等同于因果确认或审计认证。'
    pages=[]
    for idx,p in enumerate(plan,1):
        typ=p['kind']
        if typ=='cover':
            body=(f'<div class="cover-mark">专业报告 · {E(m["edition"])}</div><div class="cover-main"><p class="eyebrow">独立站经营分析 / 全面诊断</p>'
                  f'<h1>{E(m["title"])}</h1><p class="cover-subtitle">{E(m["main_question"])}</p>'
                  f'<div class="cover-accent" aria-hidden="true"><span></span><span></span><span></span></div></div>'
                  f'<dl class="cover-facts"><dt>汇报对象</dt><dd>{E(m["audience"])}</dd><dt>分析周期</dt><dd>{E(m["period"])}</dd>'
                  f'<dt>数据截至</dt><dd>{E(m["data_as_of"])}</dd><dt>编制 / 日期</dt><dd>{E(m["author"])} · {E(m["report_date"])}</dd>'
                  f'<dt>版本 / 标记</dt><dd>{E(m["edition"])} · {E(m["confidentiality"])}</dd></dl>'
                  f'<p class="cover-disclaimer">{E(tag)}。所有经营数据与界面均为合成示例。</p>')
        elif typ=='summary':
            ff=''.join(f'<div class="finding"><span class="finding-no">{i:02d}</span><p>{q(f["text"])} <sup>{source_refs(f["source_ids"])}</sup></p></div>' for i,f in enumerate(su['findings'],1))
            cards=''.join(f'<div class="kpi"><div>{E(k["label"])}</div><strong>{E(metric_text(report,k))}</strong><p>{E(k["comparison"])}</p></div>' for k in report.get('kpis',[]))
            body=f'<p class="eyebrow">核心判断 · 完整诊断版</p><h1>{E(m["title"])}</h1><p class="meta">{E(m["scope"])}<br>分析期间：{E(m["period"])}；数据截至：{E(m["data_as_of"])}</p><p class="question">核心问题：{E(m["main_question"])}</p><div class="bottom-line"><h2>总体判断</h2><p>{q(su["bottom_line"])}</p></div>{ff}<div class="decision"><h2>建议方向</h2><p>{q(su["next_step"])}</p></div><p class="caveat"><b>主要边界：</b>{q(su["critical_limit"])}</p><div class="kpis">{cards}</div>'
        elif typ=='toc':
            groups=[]
            for name,gg in groupby(enumerate(plan,1),lambda it:it[1]['chapter']):
                gg=list(gg);start,end=gg[0][0],gg[-1][0];target=gg[0][1]['id']
                span=f'{start:02d}' if start==end else f'{start:02d}—{end:02d}'
                groups.append(f'<li><a href="#{E(target)}"><span>{E(name)}</span><b>{span}</b></a></li>')
            body=f'<p class="eyebrow">目录与阅读路径</p><h2 class="section-title">先看经营全貌，再追溯问题与行动</h2><p>管理层总览不是单页摘要：先集中呈现关键数据、发现、策略和全部优先待办；后续章节分别完成证据论证、方案取舍和实施设计。</p><ol class="contents">'+''.join(groups)+f'</ol><h3>按职责阅读</h3><p><b>管理决策：</b>先读第{management}页，明确经营问题、待批准事项和资源约束。<br><b>业务执行：</b>按待办编号进入相关诊断页，再查第{execution}页的完整行动卡。<br><b>数据复核：</b>对照第{methods}页的口径与来源，使用配套JSON核对计算。</p><p class="caveat">{demo_note}页数由本次问题范围决定，不作为以后报告的固定要求。</p>'
        elif typ=='content':body=''.join(content(sections[x]) for x in p['section_ids'])
        elif typ=='visual':
            visual_note=f'<p class="caveat"><b>证据与边界：</b>{q(p["visual_note"])} 来源：{source_refs([p["evidence_source_id"]])}。</p>'
            readout_items=''.join(f'<div><strong>{E(x["value"])}</strong><span>{E(x["label"])}</span></div>' for x in p.get('readouts',[]))
            readout=(f'<div class="visual-readout"><h3>关键证据如何读</h3><div class="visual-readout-grid">{readout_items}</div>'
                     f'<p>{q(p["readout_summary"])}</p></div>') if readout_items and p.get('readout_summary') else ''
            if p['visual_kind']=='process':
                stages=''.join(f'<li><span class="step-no">{i:02d}</span><strong>{E(step)}</strong></li>' for i,step in enumerate(p['steps'],1))
                figure=(f'<figure class="process-figure"><figcaption>图示｜合成的移动端购买路径 <span>阶段顺序示意；完整分子、分母与变化见D08</span></figcaption>'
                        f'<ol class="process-steps">{stages}</ol>{readout}</figure>')
            else:
                figure=('<figure class="mock-figure"><figcaption>界面示意｜商品决策信息 <span>合成界面，无真实品牌、商品图或店铺截图</span></figcaption>'
                        '<div class="mock-browser"><div class="mock-bar"><i></i><i></i><i></i><span>示例商品详情页 · 合成</span></div>'
                        '<div class="mock-content"><div class="mock-product" aria-label="灰色商品占位图"><div class="mock-shape"></div><small>示意图占位</small></div>'
                        '<div class="mock-details"><p class="mock-kicker">商品详情 / 示例</p><h3>通用装备配件</h3>'
                        '<div class="mock-row"><b>① 适配条件</b><span>明确车型、年份及限制条件</span></div>'
                        '<div class="mock-row"><b>② 安装说明</b><span>展示步骤、工具与注意事项</span></div>'
                        '<div class="mock-row"><b>③ 交付承诺</b><span>核对库存、发货与预计送达</span></div>'
                        '<div class="mock-button">查看适配后选择</div></div></div></div>'+readout+'</figure>')
            body=f'<p class="eyebrow">可视化证据 · {E(p["label"])}</p><h2 class="section-title">{E(p["visual_title"])}</h2>{figure}{visual_note}'
        elif typ=='actions':
            body=f'<p class="eyebrow">实施台账 · 全量行动分组展开</p><h2 class="section-title">{E(p["label"])}</h2><p class="meta">角色与周期均为建议安排，负责人、资源和阈值须在启动前确认。行动编号与管理总览一致，不另建第二套待办。</p>'+''.join(action(actions[x]) for x in p['action_ids'])
        elif typ=='sources':
            entries=[]
            for x in p['source_ids']:
                s=sources[x]
                entries.append(f'<article class="source-entry" id="src-{E(x)}"><h3>{E(x)}　{E(s["title"])}</h3><p class="meta">{E(s["period"])}</p><p>{P(s["note"])}</p><p class="source">复核位置：{E(s["locator"])}</p></article>')
            provenance_note='本页列示的是合成数据字典与假设，不是已连接的真实业务系统。' if m['synthetic'] else '本页记录来源及其适用边界。'
            body=f'<p class="eyebrow">来源、证据与可复核范围</p><h2 class="section-title">{E(p["label"])}</h2>'+''.join(entries)+f'<p class="caveat">{provenance_note}程序校验不认证来源真实性；结论、对照设计与商业可行性仍需人工复核。</p>'
        elif typ=='back':
            body=(f'<div class="back-main"><p class="eyebrow">报告结束 / 版本与边界</p><h2>{E(m["title"])}</h2>'
                  f'<p class="back-line">先核实贡献、库存与购买路径，再按实测结果决定投入。</p>'
                  f'<div class="back-rule"></div><p>{E(su["critical_limit"])}</p></div>'
                  f'<div class="back-meta"><p><b>编制</b> {E(m["author"])}　<b>版本</b> {E(m["edition"])}　<b>日期</b> {E(m["report_date"])}</p>'
                  f'<p>{E(m["confidentiality"])} · 来源、计算与方法详见正文末章及配套 JSON。</p></div>')
        else: raise ValueError(f'未知页类型：{typ}')
        pages.append(f'<section class="report-page kind-{typ}" id="{E(p["id"])}"><header class="running"><span>{E(m["edition"])}</span><span>{E(tag)}</span></header><div class="page-body">{body}</div><footer><span>{E(p["chapter"])}</span><a class="back-toc" href="#{E(toc_id)}">返回目录</a><span>{idx:02d} / {total:02d}</span></footer></section>')
    return '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:; font-src \'none\'; base-uri \'none\'; form-action \'none\'"><title>'+E(m['title'])+'</title><style>'+css+'</style></head><body class="long-report"><main>'+''.join(pages)+'</main></body></html>'
